CREATE TABLE IF NOT EXISTS shirts (
  id BIGSERIAL PRIMARY KEY,
  price INTEGER,
  size VARCHAR(100),
  imgUrl VARCHAR(1024)
);

CREATE TABLE IF NOT EXISTS hoodies (
  id BIGSERIAL PRIMARY KEY,
  price INTEGER,
  size VARCHAR(100),
  imgUrl VARCHAR(1024)
);